### ISSUE TITLE
Prompt to refresh corpus no longer appears on the DToC edition interface when the source doc has changed, not even for the DToC object owner. 

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc_dtoc_edition#13]
Such was the case with https://beta.cwrc.ca/islandora/object/cwrc%3Ac5f232a0-151c-4ed9-ac58-f614e7675160

**Comment by nikathone** [comment]
This should also be fixed in dev-01 I had a small bug in the code when only one document/object was selected from the collection it will have trouble getting the data.

**Comment by ilovan** [comment]
sounds good - it seems to be fixed now
