### ISSUE TITLE
Make posible for users to create DToC object without specifying configuration if source document(s) match the DToC document template. 

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc_dtoc_edition#15]
1. User clicks "Ingest" without providing ay configuration info
Message: "You selected to create a DToC edition with a default configuration (see https://cwrc.ca/templates/DToC_Document_Template.xml) that may or may not match your source document structure. Do you wish to continue? Yes/No"

2. DToC is Created with the default config to match https://voyant-tools.org/dtoc/?corpus=379ea632e5cea145d99b4d02f580da41&docId=2f3f9cd630602f4c0f7016a9077bda89 (config is included in the module code, since if we copy it from the external Voyant corpus I linked it may fail when said corpus is removed from Voyant (no persistent URL)

**Comment by nikathone** [comment]
Added the changes in https://github.com/cwrc/cwrc_dtoc_edition/commit/b45c00dadbe7571195ea097143dbec78af581bb0

**Comment by ilovan** [comment]
confirmed
