### ISSUE TITLE
The "Documents Update status" block: how difficult would it be to turn it into a Drupal warning message?

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc_dtoc_edition#6]
(to show up only when sources changed, with sources listed and clickable and the ability to refresh the Dtoc edition)

The reason I am asking is because the sidebar is taking up a lot of space and I think we should rather have it collapsed by default (this would effectively hide the news that the documents were changed)

**Comment by ilovan** [comment]
Thanks, @nikathone .
Can you hide it from people who don't have editing permissions on the DToC object?
Currently the information is showing up to everyone: see https://dev-01.cwrc.ca/islandora/object/cwrc%3A91 logged out

**Comment by nikathone** [comment]
Ok. Only users with the ability to edit the DToC datastream should be able to see the update edition form. Also if all the sources are up to date they will still see the loader but not the form if nothing to update. The loader still showing cause I am doing some lazy loading to make the initial page load faster then check if changes available. @ilovan this is ready for review.
