### ISSUE TITLE
If user chooses to manually configure xPaths, make the document xPath a required field.

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc_dtoc_edition#7]
This is due to a change in the standalone DToC settings.

**Comment by nikathone** [comment]
Pushed an update on dev-01 and it's ready for your review.

**Comment by ilovan** [comment]
![image](https://user-images.githubusercontent.com/6600070/52751013-39f85580-2fab-11e9-94c4-90ee87c40187.png)

looks ok, maybe two improvements:

- can you add a red asterisk to the Documents field in the form to mark it as required ?
-  can we change the text of the Drupal error message to "Please configure the xPath for your documents (which will form the "chapters" of your DToC edition)."

**Comment by nikathone** [comment]
Updated and ready for your review.

**Comment by ilovan** [comment]
confirmed, thank you

**Comment by nikathone** [comment]
Feature committed in https://github.com/cwrc/cwrc_dtoc_edition/commit/b9a0e57555d47d2507fbe6a9dfca89913763ad30
