### ISSUE TITLE
Bridge editions: if user changes the label of the CWRC object, the title of the DToC corpus does not change

### ISSUE THREAD

**Issue by ilovan** [cwrc/cwrc_dtoc_edition#8]
Example:
https://beta.cwrc.ca/islandora/object/cwrc%3A97b89c10-ec48-4532-8076-8050a82f6b87

![image](https://user-images.githubusercontent.com/6600070/52738953-0c041880-2f8d-11e9-83f3-a44f00e2259c.png)

**Comment by nikathone** [comment]
Not sure why it wasn't changing it but had to go back and re-edit the DTOC datastream and now it's displaying it.

**Comment by ilovan** [comment]
should we set a trigger in the mods datastream so that if the title is changed, the DToC is also changed, with the new title provided as the corpus name?

**Comment by nikathone** [comment]
This one is ready for test on dev 01.

**Comment by nikathone** [comment]
Fixed  added in https://github.com/cwrc/cwrc_dtoc_edition/commit/5de7d8ff7692002e5fcab731ef9a23b825618eb1

**Comment by ilovan** [comment]
seems to be working now, but it also seems to suppress the workflow stamp form that should pop up when someone modifies the MODS datastream. do you have an idea why?

**Comment by ilovan** [comment]
confirmed fixed now
